language: php

php:
  - '7.3.24'
  - '7.4.3'
  - '8.0'

env:
  global:
    - XDEBUG_MODE=coverage
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: '7.4.3'
      env: TARGET=behat

  allow_failures:
    - php: '8.0'

install:
  - if [ -x .travis/install_${TARGET}.sh ]; then .travis/install_${TARGET}.sh; fi;
  - composer install

script:
  - if [ -x .travis/script_${TARGET}.sh ]; then .travis/script_${TARGET}.sh; fi;

after_success:
  - if [ -x .travis/after_success_${TARGET}.sh ]; then .travis/after_success_${TARGET}.sh; fi;
